### ISSUE TITLE
Discuss point system during a meeting/daily

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Entretenibit#10]
How many to have;
Based on fibbonaci;
Should we map work hours to them?
What should be the average/most a user should do?
Special maximum case for PO

**Comment by martchellop** [comment]
@BrunoGomesCoelho And how is going to decide how much points each tasks has?

**Comment by BrunoGomesCoelho** [comment]
@martchellop Good question; I dont remember exactly at what process we do it (maybe when the team is discussing the implementations of the sprint as choosen by the PO), but I would suggest using the each person quickly chooses a card and we average them

**Comment by martchellop** [comment]
@BrunoGomesCoelho What's the advantage of using this system? I mean, why use anyone at all?

**Comment by BrunoGomesCoelho** [comment]
@martchellop so we can more easily spread out minimum work balance;

so we hava a ideia of what to put in a sprint, after all everything that is in a sprint should be done in that time constrain

and probably most importantly, because it is based on these kind of project structuring/planning that our final grade will be based on and not the actual project

**Comment by matheushjs** [comment]
This issue has not been discussed in our May-3 meeting.
That's unfortunate.
Requesting reevaluation of whether this is a relevant issue or not.

**Comment by BrunoGomesCoelho** [comment]
I think it is a relevant issue, but until we officially start with the Scrum workflow it isn't crucial.
Maybe we can talk about it in the next meeting.

**Comment by martchellop** [comment]
Since we are not going to use this points for now, I'm going to close this issue, if necessary we can reopen it next week and discuss a point system
