### ISSUE TITLE
Risk Analisys - Is it this sprint?

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Entretenibit#104]
I am not sure if according to the [log](https://github.com/martchellop/Entretenibit/blob/master/Documents/Meetings/10-June5-meeting-secretGarden.md) of the last meeting we should also do a risk management document for this sprint, it seems so according to my interpretation.

Paging @martchellop if he agrees to officially set this as part of this sprint or not, and if so, the whole team (@LTKills @TMTiagoT @FelSiq @matheushjs ) if they agree.

**Comment by LTKills** [comment]
I think risk management should indeed be in this sprint as the grading (Software Engeneering stuff) should be prioritized.

**Comment by matheushjs** [comment]
I agree this should be on this week's sprint. It has been vaguely discussed on Monday

**Comment by martchellop** [comment]
OK, I'll create an issue for that.
