### ISSUE TITLE
Database does not follow diagram

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Entretenibit#111]
According to the output of some insertions, the "type" column does not exist in the event database:

> 	"psycopg2.ProgrammingError: column "type" of relation "event" does not exist"

Either the [documentation](https://github.com/martchellop/Entretenibit/blob/master/Documents/Construction/Database%20ER%20Diagram.pdf) should be updated or the database;

I was thinking the database was created with with this [file](https://github.com/martchellop/Entretenibit/blob/master/Documents/Construction/Database%20ER%20Diagram.pdf) but that doesn't seem to be the case. 

In any case, we should have a permanent file that logs any changes to our database if they occur. Without asking personally, I for example wouldn't know why or who changed the database.

I suggest deleting the database and recreating with this [file](https://github.com/martchellop/Entretenibit/blob/populate-DB/robot/createDB.sql) (the only change from the original is a bigger primary key).

**Comment by martchellop** [comment]
We are still developing the project and have no idea how it will end up in the future. With that in mind we have to understand that our knowledge of first creating documentation for the database and then implementing it, how it was taught in the database class it's not going to work for this case. 

After we figured it out how the database should look like more or less, there is a program called pg_dump that dumps the entire schema to a file and let's it be easily recreated.

Also, there was a mistake in the schema present in our current file, since type make have more than one value and that solutions doesn't work this way. So in order to fix this mistake, at least 2 other files should be changed (the schema and the MR drawing).

Because of all this reasons, I think there shouldn't be documentation about the database

**Comment by matheushjs** [comment]
> Because of all this reasons, I think there shouldn't be documentation about the database

I think having an MR isn't much of a help for our project, but having an updated MER might be quite useful for understanding the domain of our problem.

> Either the documentation should be updated or the database;

I've checked the table schemas here, and it seems the attribute `type` was implemented as a separate table, referenced by the `event` table. I don't think this is a good choice, as the `type` can be an INTEGER attribute.

> In any case, we should have a permanent file that logs any changes to our database if they occur. Without asking personally, I for example wouldn't know why or who changed the database.

The database has not been changed since its creation. The problem was aroused in #87 itself.

**Comment by matheushjs** [comment]
The table schemas below:

```
                                   Table "public.event"
   Column    |          Type          |                     Modifiers                      
-------------+------------------------+----------------------------------------------------
 title       | character varying(30)  | not null
 description | character varying(300) | not null
 casting     | character varying(400) | 
 link        | character varying(70)  | not null
 id          | bigint                 | not null default nextval('event_id_seq'::regclass)
Indexes:
    "event_pkey" PRIMARY KEY, btree (link)
    "id_index" UNIQUE, btree (id)
Referenced by:
    TABLE "type" CONSTRAINT "fk_event" FOREIGN KEY (event) REFERENCES event(id)
    TABLE "occurence" CONSTRAINT "occurence_event_fkey" FOREIGN KEY (event) REFERENCES event(link) ON DELETE CASCADE

           Table "public.location"
  Column  |         Type          | Modifiers 
----------+-----------------------+-----------
 name     | character varying(30) | not null
 street   | character varying(50) | not null
 number   | integer               | not null
 district | character varying(10) | 
Indexes:
    "location_pkey" PRIMARY KEY, btree (name, street, number)
Referenced by:
    TABLE "occurence" CONSTRAINT "occurence_location_name_fkey" FOREIGN KEY (location_name, location_street, location_number) REFERENCES location(name, street, number) ON DELETE CASCADE

              Table "public.occurence"
     Column      |         Type          | Modifiers 
-----------------+-----------------------+-----------
 event           | character varying(70) | not null
 location_name   | character varying(30) | not null
 location_street | character varying(50) | not null
 location_number | integer               | not null
 date            | date                  | not null
 pricing         | character varying(50) | 
Indexes:
    "occurence_pkey" PRIMARY KEY, btree (event, date)
Foreign-key constraints:
    "occurence_event_fkey" FOREIGN KEY (event) REFERENCES event(link) ON DELETE CASCADE
    "occurence_location_name_fkey" FOREIGN KEY (location_name, location_street, location_number) REFERENCES location(name, street, number) ON DELETE CASCADE

     Table "public.type"
 Column |  Type   | Modifiers 
--------+---------+-----------
 event  | integer | not null
 type   | text    | not null
Indexes:
    "type_pkey" PRIMARY KEY, btree (event, type)
    "type_idx" btree (type)
Foreign-key constraints:
    "fk_event" FOREIGN KEY (event) REFERENCES event(id)
```

**Comment by LTKills** [comment]
I believe having a MR is crucial, even in development databases. It's a lot easier to visualize a MR than the table of schemas pointed by @matheushjs. 

> After we figured it out how the database should look like more or less, there is a program called pg_dump that dumps the entire schema to a file and let's it be easily recreated.

This makes very little sense to me. If there's a program that easily creates the schema of the database couldn't we run it after every change in the database and update the documentation?

> I think having an MR isn't much of a help for our project, but having an updated MER might be quite useful for understanding the domain of our problem.

I think I didn't understand what you mean, from my point of view it would be much more useful (although we would have to constanty change it) to have the MR for a better view of the domain.

> first creating documentation for the database and then implementing it

I believe this was not what @BrunoGomesCoelho was proposing, certainly was not what I was. I'm proposing we change the database as needed and update the documentation accordingly.

**Comment by BrunoGomesCoelho** [comment]
> The database has not been changed since its creation. The problem was aroused in #76 itself.

Actually, that's not the case, the database created in #76 was later changed by @martchellop . The SQL code in that pull request does not represent the current status of the database. My problem is exactly with the fact that this is currently very hard to find.

> I believe this was not what @BrunoGomesCoelho was proposing, certainly was not what I was. I'm proposing we change the database as needed and update the documentation accordingly.

Yep, although I did mention the documentation not being in check, my biggest problem is the lack of logs for the database being different.

Just to be clear: I am not proposing in this issue to redo any documentation, just to have a single log file for now. We can have the documentation discussion personally tomorrow if needed, I just want to unblock my issue.

When Marcelo changed the database, it broke the part of populating the BD. Since it wasn't in use, no-one saw it and Marcelo didn't check it.

I now have to again change the database because the character types are too small to store some events; this will probably break something else according to Marcelo which will be hard to find out if we don't have a log for it.

I don't want to be the guy that changes the database and breaks the front-ends without logging anything, even if this is what was done last time in regards to the robot.

==========================

So just to be clear, what I am proposing that I would like to know if it is ok with you guys for now (and if necessary, the MR/MER discussion can happen tomorrow) so I can finish my issue:

I am proposing that for now the code in this [file](https://github.com/martchellop/Entretenibit/blob/master/robot/createDB.sql) represents the database, and any changes to it must go here. Then we just delete all tables and recreate them.
That way everything gets automatically logged and I don't have to message other people personally to find out who changed the bank and why.

**Comment by martchellop** [comment]
> This makes very little sense to me. If there's a program that easily creates the schema of the database couldn't we run it after every change in the database and update the documentation?

Only @matheushjs can do that since the database is running on his pc, and the format that it dumps it's that great to read.

> I think I didn't understand what you mean, from my point of view it would be much more useful (although we would have to constanty change it) to have the MR for a better view of the domain.

There are only 3/4 tables so far in this point, I think we don't need an MR for that. 

> I've checked the table schemas here, and it seems the attribute type was implemented as a separate table, referenced by the event table. I don't think this is a good choice, as the type can be just an INTEGER attribute.

I made that decision because an event can have more than one type, and putting type as a column in the event table, would repeat the tuples for every type an event has.

> I now have to again change the database because the character types are too small to store some events; this will probably break something else according to Marcelo which will be hard to find out if we don't have a log for it.

You can change the size of type in our current database and that's not going to break anything, but you use this [file](https://github.com/martchellop/Entretenibit/blob/master/robot/createDB.sql), it's going to break the interface. 

> I don't want to be the guy that changes the database and breaks the front-ends without logging anything, even if this is what was done last time in regards to the robot.

Point taken.

**Comment by BrunoGomesCoelho** [comment]
> You can change the size of type in our current database and that's not going to break anything, but if you use this file, it's going to break the interface.

Ok, for now I am going to change only the size of the type then and go back to #90.

I would recommend we change that file to represent the current status of our Database in a way that it doesn't break the interface; If I understand correctly, all that we need is get Matheus's table schema output and convert it into SQL. It would also fix the logging problem.

**Comment by matheushjs** [comment]
> Actually, that's not the case, the database created in #76 was later changed by @martchellop . The SQL code in that pull request does not represent the current status of the database. My problem is exactly with the fact that this is currently very hard to find.

Sorry, I only looked into the createDB.sql file, and it had only modifications by Gabriel. This file should hold the SQL code that creates the tables in our database, and it's crucial that the database remains consistent with this file.

So if I understood correctly, @martchellop logged in the database and changed the schemas without changing the createDB.sql file, which makes it **impossible** to track the changes, which is really harmful.

> I would recommend we change that file to represent the current status of our Database in a way that it doesn't break the interface; If I understand correctly, all that we need is get Matheus's table schema output and convert it into SQL. It would also fix the logging problem.

That's fine for me. But the biggest point here is that the database shouldn't be modified at will by a single member. If this becomes an issue I'll take permissions of changing the database to just myself.
