### ISSUE TITLE
Robot in PEP8

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#118]
The code in the /robot will have to be updated with the python standard pep8

**Comment by matheushjs** [comment]
I suggest this is done after #120 to avoid having 2 people touching the same python files.

**Comment by BrunoGomesCoelho** [comment]
#120 Has been done, will get on this.

**Comment by matheushjs** [comment]
Closed by #134

**Comment by matheushjs** [comment]
Actually, if @BrunoGomesCoelho didn't close this issue on his Pull Request, maybe he had a reason.

**Comment by BrunoGomesCoelho** [comment]
No reason except forgetting to put the Closes tag haha, closing now.
