### ISSUE TITLE
Advanced searchs

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#124]
The user has to have the option to select a few options, which already are implement in the interface, and the correspond events have to appear in the cards. 

This will include the uplift of a few component's states as well as the implementation of new endpoints in the server.

Just to make the integration a little easier, wait until issue number #123 is done.

**Comment by FelSiq** [comment]
I really not sure how the mentioned "new endpoints" should be added to the project:

`const endpoint = encodeURI(`/eventsType?type=${type}`);`
Should they be concatenated with "&" operand on the same endpoint? 
Or should exists endpoint_1, endpoint_2, ..., endpoint_n uncorrelated between each other?

**Comment by matheushjs** [comment]
I'd say it should be concatenated on the same endpoint
