### ISSUE TITLE
Deal with SQL Injection possibility introduced in #142

### ISSUE THREAD

**Issue by matheushjs** [martchellop/Entretenibit#143]
SQL Queries on #142 were implemented using concatenation of strings using the javascript operator `+=`.

This should be changed so that queries are built using query formatting functions, which are provided by the PostgreSQL library we are already using. Documentation [here](https://www.npmjs.com/package/pg-promise#query-formatting).

**Blocked** because I don't think this is to be done in the current sprint.

**Comment by FelSiq** [comment]
That's a important Issue. I agree that should be done anytime soon.
