### ISSUE TITLE
Set up the rest as Codacy team users

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [martchellop/Entretenibit#28]
As the project currently stand, only @martchellop  can change codacy settings.

Since these settings are constantly going to be updated as we fine tune for our project, we should all be able to view and change them.

Here's a quick and easy to follow link on how to do it:
https://support.codacy.com/hc/en-us/articles/208242409-Collaborators
https://support.codacy.com/hc/en-us/articles/208243169-Adding-repositories-to-a-team

**Comment by martchellop** [comment]
Guys, can you send me your emails? I need them in order to add you all to the Codacy's team

**Comment by FelSiq** [comment]
Leaving the same email that i'm registered at github:
felipe.siqueira@usp.br

**Comment by BrunoGomesCoelho** [comment]
bruno.gomes.coelho@usp.br

**Comment by matheushjs** [comment]
mhjsaldanha@gmail.com
