### ISSUE TITLE
Modelling of an event.

### ISSUE THREAD

**Issue by matheushjs** [martchellop/Entretenibit#48]

**Comment by BrunoGomesCoelho** [comment]
Some comments:

I would leave the date as a property of the event since it is the primary thing we will use to send e-mails/order by on searches

I am not sure if the entity "local" is required; are we able to sort by place/proximity in the website?

**Comment by BrunoGomesCoelho** [comment]
My comments werent even addressed :(

**Comment by matheushjs** [comment]
It's nice if the user knows where the event happens, right?

Placing date in the event is far too distant from what was in my mind.
But feel free to open another pull request with your proposed changes.
