### ISSUE TITLE
Web scrap

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#64]
Ok, this is going to be a pretty big one so I going to use this issue as reference.

You should define a page that is pretty simple to scrape and get as much information as possible. The page can be about music, workshop, theater or sports, it's up to you. Just comment which one you used.

Start getting the information of a single event and then get it from the hole page.

Once we can do the that, will have to define the database.

**Comment by martchellop** [comment]
@matheushjs Could you describe your decisions here

**Comment by BrunoGomesCoelho** [comment]
While we wait, I cant seem to out of the box run the box, so will try to make it easier to run (#73 ) so we can work on #67.

**Comment by matheushjs** [comment]
Sorry, too many e-mails regarding this project prevented me from seeing your comment @martchellop .
I'll describe as soon as I can

**Comment by matheushjs** [comment]
@martchellop @BrunoGomesCoelho 

I've described things in #78

**Comment by LTKills** [comment]
Shouldn't this be closed?

**Comment by BrunoGomesCoelho** [comment]
Think so, closing for now.
