### ISSUE TITLE
Insert in the database

### ISSUE THREAD

**Issue by martchellop** [martchellop/Entretenibit#67]
Get the information from #66 and add that to the database.

**Comment by LTKills** [comment]
As this involves creating the database as well, could you provide more info about what kind of data should the database hold? I'm thinking about doing one table to hold events.

**Comment by BrunoGomesCoelho** [comment]
So far the database definition is the one in #49. 

The associated files are  Documents/Definition/3-May28-eventRelationalModel.pdf and  Documents/Definition/3-May28-eventRelationalModel.xml.

**Comment by BrunoGomesCoelho** [comment]
@LTKills Anything you need help with that could be done?

**Comment by LTKills** [comment]
@BrunoGomesCoelho I'm thinking this issue seems pretty simple. However, the robot doesn't seem to have and API to easily get all the new events' occurrences (am I right @matheushjs ?). I believe that could be something useful, should we add an issue about that?

**Comment by BrunoGomesCoelho** [comment]
If I am not mistaken, this will do it and return a list of events:

`rb = Robot()`

`rb.scrapeAll() `

**Comment by LTKills** [comment]
In the case of conflicts (e.g. two sources with conflicting information) should we give priority to the latest intel or the one already stored in the db?

**Comment by martchellop** [comment]
An important thing to notice it's that, for a security reason, you shouldn't put the information to connect to the DB in the code. Use a .env file for that like I did in the /server code

**Comment by matheushjs** [comment]
@BrunoGomesCoelho yes, that's precisely how you use the Robot.

It returns a list of Occurences, though.

The Occurences.py file has documentation in the form commentaries that explains all attributes that an Occurence object has.

**Comment by LTKills** [comment]
@BrunoGomesCoelho I just pushed what I have done so far to insertDB. Could you check it out? I'm having some trouble dealing with the formats during the insertions. Good news is I could successfully connect and insert data into the database

**Comment by LTKills** [comment]
@martchellop I couldn't find the file you were talking about. Could you be more specific? What's it for? Why should one use it? Where can I find documentation on that?

**Comment by BrunoGomesCoelho** [comment]
The file should not exist in our code-base, that's why it can't be found.
@martchellop sent it on telegram, you need to get it from there.
The idea is that the contents of the file allows anyone to access the database, as such, it can't be publicly accessible on GitHub.

I have modified your code to work with the .env file as long as it is in the current directory. View #86.
